# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18705AEYjwDWhjYFOJ3OmLtmBvYbStHLQ
"""

import pandas as pd

"""**Loading WW2 Ships Dataset**"""

df= pd.read_csv("ships.csv")
df

"""**Checking the features of the loaded dataset**"""

print('''
****Here is the description of Dataset****
''')
print(df.describe())
print('''
****Here is the info of Dataset****
''')
df.info()
print('''
****Here is the null value sum up of Dataset****
''')
print(df.isnull().sum())
print('''
****Here is the shape and column names of Dataset****
''')
df.shape
df.columns

df.Country.head(10)
df['Country'].unique()

# removing the unnamed index column
df = pd.read_csv('ships.csv')
df = df.drop(columns=[df.columns[0]])
# Cleaning up Whitespace & Special Characters
df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)
df['Name'] = df['Name'].str.replace('LÃ¼deritz', 'Lüderitz', regex=False)

# Cleaning 'Launch Year' (Convert empty strings/spaces to actual NaN, then convert to numeric/nullable integer)
df['Launch Year'] = pd.to_numeric(df['Launch Year'].replace('', pd.NA), errors='coerce').astype('Int64')

# Handling Missing Values in Categorical Columns (Replacing empty class/country with 'Unknown')
df['Class'] = df['Class'].fillna('Unknown')
df['Country'] = df['Country'].fillna('Unknown')

# Removing all Duplicates
df = df.drop_duplicates()
# df.head(10)
df.tail(10)

"""**Now i have the cleaned version of this dataset**

**Following are the 8 specific business questions about this whole procedure with code sections of each question separately**

1. Which country built the most ships?
"""

df.Country.value_counts()

"""**Answer:** As per the results Germany made the most ships

2. What are the most common ship classes overall?
"""

df.Class.value_counts()

"""**Answer:** As per the results most common ship classes overall if we give the top 3 rankings are as follows:
1. M-class Minesweeper
2. Type VII-class Submarine
3. Balao-class Submarine

3. Did shipbuilding activity increase or decrease as the war went on?
"""

df.groupby('Country')['Launch Year'].value_counts()

ship_production_by_year = df.groupby('Launch Year').size().reset_index(name='Number of Ships')
ship_production_by_year = ship_production_by_year.sort_values(by='Launch Year')

print(ship_production_by_year)

"""**Answer:** As per the results the shipbulding activity increased as the war went on, bu in 1945 and 1946 only 4 ships in total were built

4. Which country was building the widest variety of ship classes?
"""

df.groupby('Country')['Class'].value_counts()

variety_by_country = df.groupby('Country')['Class'].nunique().sort_values(ascending=False)
print(variety_by_country)

"""**Answer:** The country with the highest number of widest ship varieties is USA.

5. What's the most common ship class for each of the top 3 countries?
"""

top_3_countries = variety_by_country.head(3).index.tolist()

print(top_3_countries)

# excluding 'No Classification'
for country in top_3_countries:
    country_df = df[df['Country'] == country]

    filtered_classes = country_df['Class'][country_df['Class'] != 'No Classification']

    if not filtered_classes.empty:
        most_common_class = filtered_classes.value_counts().idxmax()
        count_of_class = filtered_classes.value_counts().max()
        print(f"The most common ship class for {country} is '{most_common_class}' with {count_of_class} units.\n")
    else:
        print(f"No other classified ships found for {country} besides 'No Classification'.\n")

"""**Answer:** The most common ship class for each of the top 3 countries (United States, Japan, and Germany) is displayed above.

**Answer:**

6. How much missing data is there in Launch Year, and does it differ by country?
"""

total_missing_launch_year = df['Launch Year'].isnull().sum()
print(total_missing_launch_year)
missing_launch_year_by_country = df.groupby('Country')['Launch Year'].apply(lambda x: x.isnull().sum()).sort_values(ascending=False)
display(missing_launch_year_by_country)

"""**Answer:** The total number of missing 'Launch Year' values is **717** and their distribution by country are displayed above. This shows how much missing data there is and **Germany** contributes the most to it as if we talk about the most missing values of launch year countrywise.

7. Which country had the earliest and latest ship launches on record?
"""

print(df['Launch Year'])
min_yr= df['Launch Year'].min()
print(min_yr)
max_yr= df['Launch Year'].max()
print(max_yr)

valid_launch_years = df['Launch Year'].dropna()
valid_launch_years = valid_launch_years[valid_launch_years != 0]

min_yr = valid_launch_years.min()
max_yr = valid_launch_years.max()
print('''
Min_yr & Max_yr after dropping null values:
''')
print(min_yr)
print(max_yr)

earliest_launch_country = df[df['Launch Year'] == min_yr]['Country'].iloc[0]
latest_launch_country = df[df['Launch Year'] == max_yr]['Country'].iloc[0]

print(earliest_launch_country,min_yr)
print(latest_launch_country,max_yr)

"""**Answer:** USA was the earliest & France is the Latest according to this dataset

8. Which country had the widest range of Launch Years — meaning the longest shipbuilding history in this dataset?
"""

df.describe()

widest_launch_yrs= df.groupby('Country')['Launch Year']
display(widest_launch_yrs)

cleaned_df = df[df['Launch Year'].notna() & (df['Launch Year'] != 0)].copy()

launch_year_summary = cleaned_df.groupby('Country')['Launch Year'].agg(['min', 'max'])

# Calculating the range
launch_year_summary['range'] = launch_year_summary['max'] - launch_year_summary['min']

sorted_ranges = launch_year_summary.sort_values(by='range', ascending=False)
display(sorted_ranges)


longest_history_country = sorted_ranges.index[0]
longest_history_range = sorted_ranges['range'].iloc[0]

"""**Answer:** The USA had the widest range of Launch Years, indicating the longest shipbuilding history in this dataset."""