import unittest
from inference import InferenceModel

class TestInferenceModel(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # We assume final_model_pipeline.joblib has been generated by execute_capstone.py
        try:
            cls.model = InferenceModel('final_model_pipeline.joblib')
        except FileNotFoundError:
            cls.model = None

    def test_valid_input(self):
        if not self.model:
            self.skipTest("Model file not found.")
        
        sample_data = {
            'age': 39, 'workclass': 'State-gov', 'fnlwgt': 77516, 'education': 'Bachelors',
            'education-num': 13, 'marital-status': 'Never-married', 'occupation': 'Adm-clerical',
            'relationship': 'Not-in-family', 'race': 'White', 'sex': 'Male', 'capital-gain': 2174,
            'capital-loss': 0, 'hours-per-week': 40, 'native-country': 'United-States'
        }
        res = self.model.predict_single(sample_data)
        self.assertIn('probability', res)
        self.assertIn('prediction', res)
        self.assertIn('top_3_features', res)
        self.assertEqual(len(res['top_3_features']), 3)

    def test_missing_column(self):
        if not self.model:
            self.skipTest("Model file not found.")
            
        sample_data = {
            'age': 39, 'workclass': 'State-gov'
            # Missing other required columns
        }
        with self.assertRaises(ValueError) as context:
            self.model.predict_single(sample_data)
        self.assertIn("Missing required column", str(context.exception))

    def test_unseen_category(self):
        if not self.model:
            self.skipTest("Model file not found.")
            
        sample_data = {
            'age': 39, 'workclass': 'Unknown-Workclass-123', 'fnlwgt': 77516, 'education': 'Bachelors',
            'education-num': 13, 'marital-status': 'Never-married', 'occupation': 'Adm-clerical',
            'relationship': 'Not-in-family', 'race': 'White', 'sex': 'Male', 'capital-gain': 2174,
            'capital-loss': 0, 'hours-per-week': 40, 'native-country': 'United-States'
        }
        # The pipeline has handle_unknown='ignore' in OneHotEncoder, so this should not raise an error
        # but silently ignore the unseen category and predict normally.
        res = self.model.predict_single(sample_data)
        self.assertIn('probability', res)

if __name__ == '__main__':
    unittest.main()
